import os
import time
import shutil
import logging
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

version: '3.8'

services:
  backup_daemon:
    build: .
    volumes:
      - /path/to/source_folder:/path/to/source_folder
      - /path/to/backup_folder:/path/to/backup_folder
    restart: always
