# Використаємо образ GCC як базовий
FROM gcc:latest

# Створення робочого каталогу
WORKDIR /usr/src/app

# Копіювання всіх файлів до робочого каталогу
COPY . .

# Виконання препроцесингу, компіляції, асемблювання, лінкування, оптимізації та профайлінгу
RUN gcc -E preprocessor_example.c -o preprocessor_output.c && \
    gcc -c example.c -o example.o && \
    gcc -S example.c -o example.s && \
    gcc -c lib.c -o lib.o && \
    gcc -c main.c -o main.o && \
    gcc main.o lib.o -o program && \
    gcc -O0 optimization_example.c -o optimization_example_O0 && \
    gcc -O1 optimization_example.c -o optimization_example_O1 && \
    gcc -O2 optimization_example.c -o optimization_example_O2 && \
    gcc -O3 optimization_example.c -o optimization_example_O3 && \
    gcc -pg optimization_example.c -o optimization_example

# Виконання основної програми після зборки
CMD ["./program"]
