# Використовуємо базовий образ з компілятором gcc
FROM gcc:latest

# Створюємо робочу директорію
WORKDIR /app

# Копіюємо вихідний код до контейнера
COPY file.c /app/file.c

# Компілюємо програму
RUN gcc -o file file.c

# Налаштовуємо ENTRYPOINT для передачі аргументів програмі
ENTRYPOINT ["./file"]