FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    gcc \
    make \
    && apt-get clean

WORKDIR /app

COPY task1.c .

RUN gcc -o task1 task1.c

CMD ["./task1"]

# docker build -t task1 .
# docker run --rm task1