# Використовуємо базовий образ з компілятором GCC
FROM gcc:latest

# Копіюємо вихідний код у контейнер
COPY memory_management.c /usr/src/myapp/memory_management.c

# Переходимо до робочої директорії
WORKDIR /usr/src/myapp

# Компілюємо програму
RUN gcc -o memory_management memory_management.c

# Вказуємо команду за замовчуванням
CMD ["./memory_management"]
