# Використовуємо конкретну версію Ubuntu для стабільності
FROM ubuntu:latest

# Встановлюємо змінну середовища для уникнення інтерактивних запитів під час установки
ENV DEBIAN_FRONTEND=noninteractive

# Оновлюємо пакети та встановлюємо необхідні утиліти
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        binutils \
        vim \
    && rm -rf /var/lib/apt/lists/*

# Встановлюємо робочу директорію
WORKDIR /tmp

# Копіюємо вихідні файли
COPY . /app

# Компіляція програми
RUN gcc -pg -o /tmp/example /app/example.c

# Вказуємо команду за замовчуванням
CMD ["/bin/bash"]

# docker build -t example_profiler .
# docker run --rm example_profiler ./example
# docker run --rm example_profiler ls -la /tmp

# docker run --name profiler_temp example_profiler ./example
# docker cp profiler_temp:/tmp/gmon.out ./gmon.out
# docker cp profiler_temp:/tmp/example ./example
# docker rm -f profiler_temp

# gprof ./example gmon.out > profiling_report.txt

